package exception_handling;

import java.util.Scanner;

/**
 *
 * @author gabi
 */
public class Exception_Handling {

    public static void main(String[] args) {
        Scanner input = new Scanner(System.in);
//        int x = 1;
//
//        do {     //Addig fut újra és újra amíg exception-t talál.
//            try {
//                System.out.println("Add meg az első számot: ");
//                int n1 = input.nextInt();
//                System.out.println("Add meg a második számot: ");
//                int n2 = input.nextInt();
//                int sum = n1 / n2;
//                System.out.println(sum);
//                x = 2;
//            } catch (Exception e) {
//                System.out.println("Ezt nem teheted, próbáld újra");
//            }
//        } while (x == 1);

       
        
        // Másik
//        int x, y;
//
//        try {
//            x = (Integer) null;
//            y = (Integer) null;
//
//            // egy kcisit később...
//            System.out.println("Produkt: " + x * y);
//
//        } catch (NullPointerException e) {
//            System.out.println("Notify the developer of this exception");
//        } finally {
//            //Clean-up
//            System.out.println("Finally here");
//        }

    }

}
